### ISSUE TITLE
Manage fields, sort order

### ISSUE THREAD

**Issue by markov2** [ctrlo/GADS#107]
When dragging and dropping fields to order them, it is not possible to take the ruler left from the first word.  This was the first place I went.

The empty <code>&lt;td&gt;</code> which leads each line should get the <code>class</code> attributes "drag ui-sortable-handle" as well.   (It would also be possible to remove the first column, adding padding to the next column via CSS)

**Comment by abeverley** [comment]
This is a slightly unusual use-case as it only applies to internal columns (which can't be edited). Other columns have an edit link in that empty ```<td>```. The latter is not draggable, as otherwise it sometimes drags when trying to click on it.

Anyway, I've hopefully made things clearer in 3b4f0924
