### ISSUE TITLE
Inconsistent buttons in Manage Fields

### ISSUE THREAD

**Issue by markov2** [ctrlo/GADS#108]
Two differences with other uses of buttons in
![Screenshot from 2019-08-27 11-09-51](https://user-images.githubusercontent.com/3228759/63758097-89550200-c8bb-11e9-8f41-d0429cfc3428.png)

- [x] the top one has underline text.
- [ ] the bottom one is above the thin line: on other pages, the final submission button is below that line.

**Comment by abeverley** [comment]
Thanks @markov2 . Ticket raised internally.
