### ISSUE TITLE
Breadcrumb of graphs

### ISSUE THREAD

**Issue by markov2** [ctrlo/GADS#110]
The breadcrumb for the "Graphs" choices are not consistent:

1. Home / $table / records / manage graphs
2. Home / $table / records / graphs / new graph
3. Home / $table / records / graphs / metrics
4. Home / $table / records / graphs / metrics / new metric

- In case 4, click 'metrics' gives an error.
- Why is 'records' in the path?
- Why is 'graph' not in the first path?

Suggestion:
1. Home / $table / graphs (should also explain the existence of metrics)
2. Home / $table / graphs / add a graph   (consistent with "Add a Field" etc)
3. Home / $table / graphs / metrics
4. Home / $table / graphs / add a metric

**Comment by abeverley** [comment]
Updates in 2fd6706, e5ca6f3, fe9340a, 3da5ff5 and 7868f0e

"records" is in the breadcrumb as most users will arrive at the graphs pages from the records pages, and in many ways graphs is a subset of viewing records.
