### ISSUE TITLE
DBI Exception

### ISSUE THREAD

**Issue by tacgnol** [ctrlo/GADS#139]
Using GADS instance with seed-database.pl with or without additional tables and fields:

If viewing records and click on "View on Timeline" icon,  GUI produces "PANIC: An unexpected error has occured".

web-server error log produces:

panic: DBI Exception: DBD::Pg::st execute failed: ERROR:  column "record_created_date" does not exist
LINE 2:                         WHEN ("record_created_date" >= '2020...
                                      ^ [for Statement "SELECT "me"."id" FROM (SELECT "me"."id", ( (SELECT "me_created_date"."created" FROM "record" "me_created_date" WHERE ( "me_created_date"."id" IN ( SELECT MIN( "records_alias"."id" ) FROM "record" "records_alias" WHERE ( "records_alias"."current_id" = "me"."id" ) ) )) ) AS "record_created_date", ( (SELECT "me_created"."createdby" FROM "record" "me_created" WHERE ( "me_created"."id" IN ( SELECT MIN( "records_alias"."id" ) FROM "record" "records_alias" WHERE ( "records_alias"."current_id" = "me"."id" ) ) )) ) AS "record_created_user", ( (SELECT "createdby"."value" FROM "record" "me_created_value" LEFT JOIN "user" "createdby" ON "createdby"."id" = "me_created_value"."createdby" WHERE ( "me_created_value"."id" IN ( SELECT MIN( "records_alias"."id" ) FROM "record" "records_alias" WHERE ( "records_alias"."current_id" = "me"."id" ) ) )) ) AS "record_created_value" FROM "current" "me" LEFT JOIN "record" "record_single" ON "record_single"."current_id" = "me"."id" LEFT JOIN "record" "record_later" ON ( ( "record_later"."created" > record_single.created OR ( "record_later"."created" = record_single.created AND "record_later"."id" > record_single.id ) ) AND "record_later"."approval" = ? AND "record_later"."current_id" = "record_single"."current_id" ) WHERE ( ( ( "me"."id" IN ( SELECT "me"."id" FROM "current" "me" LEFT JOIN "record" "record_single" ON "record_single"."current_id" = "me"."id" LEFT JOIN "record" "record_earlier" ON ( ( "record_earlier"."created" < record_single.created OR ( "record_earlier"."created" = record_single.created AND "record_earlier"."id" < record_single.id ) ) AND "record_earlier"."approval" = ? AND "record_earlier"."current_id" = "record_single"."current_id" ) WHERE ( ( "record_single"."created" >= ? AND "me"."instance_id" = ? AND "me"."deleted" IS NULL AND "me"."parent_id" IS NULL AND "me"."draftuser_id" IS NULL AND "record_earlier"."id" IS NULL ) ) GROUP BY "me"."id" ORDER BY "me"."id" ASC ) OR "record_single"."created" >= ? ) AND "me"."instance_id" = ? AND "me"."deleted" IS NULL AND "me"."parent_id" IS NULL AND "me"."draftuser_id" IS NULL AND "record_later"."current_id" IS NULL ) ) GROUP BY "me"."id" ORDER BY LEAST( min(CASE
                        WHEN ("record_created_date" >= '2020-04-02 20:47:33+0000') THEN "record_created_date"
                        ELSE NULL END), min(CASE
                        WHEN ("record_single"."created" >= '2020-04-02 20:47:33+0000') THEN "record_single"."created"
                        ELSE NULL END) ) ASC LIMIT ?) "me"" with ParamValues: 1='0', 2='0', 3='2020-04-02 20:47:33', 4='2', 5='2020-04-02 20:47:33', 6='2', 7='100']
 at /srv/GADS/public/../lib/GADS.pm line 99

**Comment by abeverley** [comment]
Thanks for reporting this. It looks like something to do with the "date record created" field. As a workaround, you should be able to create a view without that field in. Or, if that field is necessary for plotting on the timeline, another workaround would be to created a calculated field that outputs the same information. Post a comment here if you need more information on how to do that.

**Comment by tacgnol** [comment]
Workaround with view works fine. I think I also know how to create a calculated field, but I'm now encountering another issue. If i go to edit or add any fields in any of the tables I now get another PANIC message, and this in the logs. I was editing a field just before this occurred but I don't recall exactly what I did.

Apr  3 14:00:27 www GADS[82028]: Failed to render template: undef error - Can't call method "all" on an undefined value at /srv/GADS/public/../lib/GADS/Layout.pm line 871.
Apr  3 14:00:27 www GADS[82028]:  at /usr/local/lib/perl5/site_perl/Dancer2/Core/Role/Template.pm line 136.
Apr  3 14:00:27 www GADS[82028]:  at /usr/local/lib/perl5/site_perl/Dancer2/Core/Hook.pm line 33
Apr  3 14:00:27 www GADS[82028]: Dancer2::Plugin::LogReport::__ANON__("Dancer2::Core::App=HASH(0x80aa99ae0)", "Failed to render template: und...[138 chars more]...e/Role/Template.pm line 136.\n") at /usr/local/lib/perl5/site_perl/Dancer2/Core/Hook.pm line 33
Apr  3 14:00:27 www GADS[82028]: (eval)("Dancer2::Core::App=HASH(0x80aa99ae0)", "Failed to render template: und...[138 chars more]...e/Role/Template.pm line 136.\n") at /usr/local/lib/perl5/site_perl/Dancer2/Core/Hook.pm line 33
Apr  3 14:00:27 www GADS[82028]: Dancer2::Core::Hook::__ANON__("Dancer2::Core::App=HASH(0x80aa99ae0)", "Failed to render template: und...[138 chars more]...e/Role/Template.pm line 136.\n") at /usr/local/lib/perl5/site_perl/Dancer2/Plugin.pm line 597
Apr  3 14:00:27 www GADS[82028]: Dancer2::Plugin::__ANON__("Dancer2::Core::App=HASH(0x80aa99ae0)", "Failed to render template: und...[138 chars more]...e/Role/Template.pm line 136.\n") at /usr/local/lib/perl5/site_perl/Dancer2/Core/App.pm line 35
Apr  3 14:00:27 www GADS[82028]: Dancer2::Core::App::__ANON__("CODE(0x80b2520f0)", "Dancer2::Core::App=HASH(0x80aa99ae0)", "Failed to render template: und...[138 chars more]...e/Role/Template.pm line 136.\n") at /usr/local/lib/perl5/site_perl/Dancer2/Core/App.pm line 1178
Apr  3 14:00:27 www GADS[82028]: (eval)("CODE(0x80b2520f0)", "Dancer2::Core::App=HASH(0x80aa99ae0)", "Failed to render template: und...[138 chars more]...e/Role/Template.pm line 136.\n") at /usr/local/lib/perl5/site_perl/Dancer2/Core/App.pm line 1179
Apr  3 14:00:27 www GADS[82028]: Dancer2::Core::App::__ANON__("Dancer2::Core::App=HASH(0x80aa99ae0)", "Failed to render template: und...[138 chars more]...e/Role/Template.pm line 136.\n") at /usr/local/lib/perl5/site_perl/Dancer2/Core/Role/Hookable.pm line 115
Apr  3 14:00:27 www GADS[82028]: Dancer2::Core::Role::Hookable::execute_hook("Dancer2::Core::App=HASH(0x80aa99ae0)", "core.app.route_exception", "Dancer2::Core::App=HASH(0x80aa99ae0)", "Failed to render template: und...[138 chars more]...e/Role/Template.pm line 136.\n") at /usr/local/lib/perl5/site_perl/Dancer2/Core/App.pm line 678
Apr  3 14:00:27 www GADS[82028]: Dancer2::Core::App::__ANON__("CODE(0x80273e5d0)", "Dancer2::Core::App=HASH(0x80aa99ae0)", "core.app.route_exception", "Dancer2::Core::App=HASH(0x80aa99ae0)", "Failed to render template: und...[138 chars more]...e/Role/Template.pm line 136.\n") at (eval 217) line 1
Apr  3 14:00:27 www GADS[82028]: Dancer2::Core::App::__ANON__("Dancer2::Core::App=HASH(0x80aa99ae0)", "core.app.route_exception", "Dancer2::Core::App=HASH(0x80aa99ae0)", "Failed to render template: und...[138 chars more]...e/Role/Template.pm line 136.\n") at (eval 219) line 2
Apr  3 14:00:27 www GADS[82028]: Dancer2::Core::App::execute_hook("Dancer2::Core::App=HASH(0x80aa99ae0)", "core.app.route_exception", "Dancer2::Core::App=HASH(0x80aa99ae0)", "Failed to render template: und...[138 chars more]...e/Role/Template.pm line 136.\n") at /usr/local/lib/perl5/site_perl/Dancer2/Core/App.pm line 1637
Apr  3 14:00:27 www GADS[82028]: Dancer2::Core::App::response_internal_error("Dancer2::Core::App=HASH(0x80aa99ae0)", "Failed to render template: und...[138 chars more]...e/Role/Template.pm line 136.\n") at /usr/local/lib/perl5/site_perl/Dancer2/Core/App.pm line 1611
Apr  3 14:00:27 www GADS[82028]: Dancer2::Core::App::_dispatch_route("Dancer2::Core::App=HASH(0x80aa99ae0)", "Dancer2::Core::Route=HASH(0x80c8a2c00)") at /usr/local/lib/perl5/site_perl/Dancer2/Core/App.pm line 1488
Apr  3 14:00:27 www GADS[82028]: Dancer2::Core::App::dispatch("Dancer2::Core::App=HASH(0x80aa99ae0)", "HASH(0x80ed8d1b0)") at /usr/local/lib/perl5/site_perl/Dancer2/Core/App.pm line 1390
Apr  3 14:00:27 www GADS[82028]: Dancer2::Core::App::__ANON__() at /usr/local/lib/perl5/site_perl/Dancer2/Core/App.pm line 35
Apr  3 14:00:27 www GADS[82028]: Dancer2::Core::App::__ANON__("CODE(0x80e524a50)") at /usr/local/lib/perl5/site_perl/Dancer2/Core/App.pm line 1390
Apr  3 14:00:27 www GADS[82028]: (eval)("CODE(0x80e524a50)") at /usr/local/lib/perl5/site_perl/Dancer2/Core/App.pm line 1392
Apr  3 14:00:27 www GADS[82028]: Dancer2::Core::App::__ANON__("HASH(0x80ed8d1b0)") at /usr/local/lib/perl5/site_perl/Plack/Middleware/Conditional.pm line 16
Apr  3 14:00:27 www GADS[82028]: Plack::Middleware::Conditional::call("Plack::Middleware::Conditional=HASH(0x80c708e40)", "HASH(0x80ed8d1b0)") at /usr/local/lib/perl5/site_perl/Plack/Component.pm line 50
Apr  3 14:00:27 www GADS[82028]: Plack::Component::__ANON__("HASH(0x80ed8d1b0)") at /usr/local/lib/perl5/site_perl/Plack/Middleware/FixMissingBodyInRedirect.pm line 50
Apr  3 14:00:27 www GADS[82028]: Plack::Middleware::FixMissingBodyInRedirect::call("Plack::Middleware::FixMissingBodyInRedirect=HASH(0x80c809f90)", "HASH(0x80ed8d1b0)") at /usr/local/lib/perl5/site_perl/Plack/Component.pm line 50
Apr  3 14:00:27 www GADS[82028]: Plack::Component::__ANON__("HASH(0x80ed8d1b0)") at /usr/local/lib/perl5/site_perl/Plack/Middleware/Head.pm line 10
Apr  3 14:00:27 www GADS[82028]: Plack::Middleware::Head::call("Plack::Middleware::Head=HASH(0x80c708ae0)", "HASH(0x80ed8d1b0)") at /usr/local/lib/perl5/site_perl/Plack/Component.pm line 50
Apr  3 14:00:27 www GADS[82028]: Plack::Component::__ANON__("HASH(0x80ed8d1b0)") at /usr/local/lib/perl5/site_perl/Plack/Util.pm line 145
Apr  3 14:00:27 www GADS[82028]: (eval)("HASH(0x80ed8d1b0)") at /usr/local/lib/perl5/site_perl/Plack/Util.pm line 145
Apr  3 14:00:27 www GADS[82028]: Plack::Util::run_app("CODE(0x80c809fd8)", "HASH(0x80ed8d1b0)") at /usr/local/lib/perl5/site_perl/Plack/Handler/FCGI.pm line 147
Apr  3 14:00:27 www GADS[82028]: Plack::Handler::FCGI::run("Plack::Handler::FCGI=HASH(0x800b0aaf8)", "CODE(0x80c809fd8)") at /srv/GADS/public/dispatch.fcgi line 19

**Comment by abeverley** [comment]
Hmmm, not sure how it's happened (as it shouldn't allow you) but it looks like you have a related field defined (either a record from other table or automatic value of other sheet) and don't have a related table defined.

This database command will try and identify the field in question:

```select name from layout left join curval_fields on parent_id=layout.id where type='curval' and curval_fields.id is null;```

Or maybe this:

```select name from layout where type='autocur' and related_field is null;```

**Comment by tacgnol** [comment]
thanks. Not sure how I managed to get tangled up but I've fixed the issue now.

**Comment by abeverley** [comment]
Thanks. If you manage to repeat the issue in the future and can then post the details then that would be great. I'll leave this issue open in the meantime.

**Comment by abeverley** [comment]
The original issue in this ticket has been fixed in 60b075fa. The second issue will be picked up as part of a more general rewrite.
