### ISSUE TITLE
Record Approval fails

### ISSUE THREAD

**Issue by tacgnol** [ctrlo/GADS#140]
Approving records fails due to missing / in URL.

Link for approvals is, e.g. https://www.redacted.uk:8443/table6approval/

If I add / in URL all works as expected, e.g.  https://www.redacted.uk:8443/table6/approval/

**Comment by abeverley** [comment]
Thanks, fixed in 2c47ea68.

Just a word of warning: the approval feature is a bit of an experimental feature. It's not currently in use in production anywhere and hasn't been tested recently. Bug reports and feedback welcome though.
