### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by cliveeisen** [ctrlo/GADS#41]
After install - app starts fine

Request password reset - get the email

Follow the link and get the password

Login silently fails with no error

[gads.log](https://github.com/ctrlo/GADS/files/2176036/gads.log)

**Comment by abeverley** [comment]
Are you running the application locally using http (rather than https)? If so, make sure you have ```is_secure``` is set to ```0``` in the session settings in config.yml

**Comment by cliveeisen** [comment]
I am and I have

engines:
  session:
    YAML:
      session_dir: "/tmp/dancer-sessions"
      cookie_duration: 3600
      cookie_name: linkspace.session
      is_secure: 0

—
Clive Eisen
GPG: 3818B5F1

**Comment by abeverley** [comment]
Hmmm, I'm not sure I'm afraid. The logs show a successful login, and then shortly after ```Auth::Extensible``` says that login is required. That would normally indicate some sort of cookie problem. Can you have a poke around in ```Dancer2::Plugin::Auth::Extensible``` and see if you can work out where it's failing please?

**Comment by cliveeisen** [comment]
Thanks Andy - will do

—
Clive Eisen
GPG: 3818B5F1

**Comment by cliveeisen** [comment]
OK it’s sorted, though I don;t quite understand

The cookie was not being set at all - which was the issue

I eventually tracked it down
If I comment OUT 'is_secure' it works
setting it to 0 does not

hey ho

Thanks for the pointers

Regards

—
Clive Eisen
GPG: 3818B5F1

**Comment by abeverley** [comment]
Thanks - I've added a comment to the example config as such.
