### ISSUE TITLE
Massive critical problem with exception handling

### ISSUE THREAD

**Issue by ribasushi** [ctrlo/GADS#7]
Sorry I fell off yesterday - something else jumped out. I am going to try to fix our original issue today, but in the meantime you have a much bigger trouble: b035928d7a (and likely other) incomplete changes of `s/eval/try/` completely broke your logic.

The gist is that `try` [**does not** set `$@`](https://metacpan.org/source/ETHER/Try-Tiny-0.24/lib/Try/Tiny.pm#L98-100) (the docs of T::T do not in fact state this this in bold letters, likely something to fix). You can observe your problem as follows:
```
perl -MTry::Tiny -e '
  eval { die "first visible exception" };
  warn $@;
  try { die "you will never see this" };
  warn $@;
'
```

This does not affect what I am debugging, so no hurry from my side at all. I am just pointing this out to you in general, as it needs fixing yesterday.

**Comment by abeverley** [comment]
Thanks @ribasushi - I appreciate it.

I'm using ```Log::Report``` instead of ```Try::Tiny``` though, which seems to be okay, unless I'm missing something?

```
perl -MLog::Report -e '
  eval { die "first visible exception" };
  warn $@;
  try { die "you will never see this" };
  warn $@;
'
```

```
first visible exception at -e line 2.
try-block stopped with ERROR: you will never see this at -e line 4. at -e line 5.
```

**Comment by ribasushi** [comment]
I am really off my game these days - I saw `try` and blindly assumed `Try::Tiny`. Disregard this report entirely, sigh... :/

**Comment by abeverley** [comment]
Thanks - better safe than sorry!
