### ISSUE TITLE
Deleting Tables Broken

### ISSUE THREAD

**Issue by tomhukins** [ctrlo/GADS#80]
Hi,
On master as of 04e47cd8eda2dd6 I can no longer delete tables.  I see the error `All fields must be deleted from this table before it can be deleted`.  I haven't created any fields, but when I look in the `layout` table using `psql`, I see various metadata fields, such as `createdby` and `createddate`.
From a quick investigation, it looks like 7eccdb4 moved the internal columns into the database itself, and I guess their existence causes table deletion to fail.
I discovered this by running the _create view_ database test:
```
webdriver/t/create_view.t .. 12/? 
#   Failed test 'A success message is visible'                                 
#   at webdriver/t/lib/Test/GADSDriver.pm line 127.                            
# No element matching '.messages .alert-success' found                         

#   Failed test 'No error message is visible'                                  
#   at webdriver/t/lib/Test/GADSDriver.pm line 110.                            
#                   'ERROR: All fields must be deleted from this table before it can be deleted'
#           matches '(?^u:\bERROR: )'
# Looks like you failed 2 tests of 13.
webdriver/t/create_view.t .. Dubious, test returned 2 (wstat 512, 0x200)       
Failed 2/13 subtests 
webdriver/t/login.t ........ ok
```

**Comment by abeverley** [comment]
Thanks Tom, fixed in 00e52f24
